FROM ubuntu:18.04
RUN apt-get update -y && apt-get install -y openjdk-8-jdk build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libreadline-dev libffi-dev wget tar libbz2-dev python-lzma liblzma-dev lzma git && apt-get remove -y python && apt-get autoremove -y
WORKDIR /python
RUN wget https://www.python.org/ftp/python/3.7.16/Python-3.7.16.tar.xz && tar -xvf Python-3.7.16.tar.xz && cd Python-3.7.16 && ./configure --enable-optimizations && make -j $(nproc) && make install 
COPY ./requirements.txt /python/Python-3.7.16/requirements.txt
RUN  pip3 install -r requirements.txt